api:
  insecure: true 
   # Enable insecure API, you may want to disable this in production
  dashboard: true
entryPoints:
  web:
    address: ":80"  # HTTP port
  websecure:
    address: ":443"  # HTTPS port
 
  
providers:
  docker: {}  # Enable Docker provider

# http:
#   routers:
#     app:
#       rule: "Host(`dev.localhost`)"
#       entryPoints:
#         - websecure
#       tls:
#         certResolver: selfsigned
#       service: app


tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/server.crt
        keyFile: /certs/server.key
  
  certificates:
    - certFile: /certs/server.crt
      keyFile: /certs/server.key
      stores:
        - default


