name: Docker build and deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to docker hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build docker image
              run: docker-compose build

            - name: Push docker image
              run: docker-compose push

            - name: SSh into EC2
              uses: appleboy/ssh-action@v0.3.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  run: |
                    docker compose pull
                    docker compose up 
