name: Docker build and deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to docker hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build docker image
              run: |
               docker build -t sulavadk7/wp-image:stable .
               docker push sulavadk7/wp-image:stable

            - name: SSh into EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                run: |
                 sudo docker pull ${{ secrets.DOCKER_USERNAME }}/wp-image:stable && sudo docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/wp-image:stable

                  

            
 
                #   run: |
                #     scp -i ${{ secrets.KEY }} docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/docker
                #     docker compose -f /home/ubuntu/docker/docker-compose.yml pull
                #     docker compose -f /home/ubuntu/docker/docker-compose.yml up 
